In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [8]:
#with open('D:/OneDrive/OneDrive - SINCRONICA/Área de Trabalho/Curso - Formação Inteligência Artificial e Machine Learning/Projetos/ai/Transacoes.txt', 'r') as f:  
with open('../Transacoes.txt', 'r') as f:  
    transactions = [line.strip().split(",") for line in f.readlines()]

transactions

[['PAINEL', 'BANCOS', 'BOLSA DA PORTA', 'ESTRIBO'],
 ['BANCOS', 'ALARME', 'BOLSA DA PORTA'],
 ['PAINEL', 'ALARME', 'ESTRIBO'],
 ['BANCOS', 'PAINEL', 'ESTRIBO'],
 ['BOLSA DA PORTA', 'PAINEL', 'ALARME'],
 ['PAINEL', 'ALARME', 'ESTRIBO', 'BANCOS'],
 ['BANCOS', 'BOLSA DA PORTA', 'ESTRIBO'],
 ['PAINEL', 'BANCOS', 'ALARME', 'ESTRIBO'],
 ['BOLSA DA PORTA', 'ALARME', 'ESTRIBO'],
 ['PAINEL', 'ALARME', 'BANCOS'],
 ['BANCOS', 'BOLSA DA PORTA', 'PAINEL'],
 ['PAINEL', 'ESTRIBO', 'BANCOS'],
 ['BANCOS', 'ALARME', 'BOLSA DA PORTA', 'ESTRIBO'],
 ['PAINEL', 'ALARME', 'BANCOS', 'ESTRIBO'],
 ['BOLSA DA PORTA', 'PAINEL', 'ALARME', 'ESTRIBO'],
 ['ALARME', 'ESTRIBO', 'BANCOS'],
 ['BANCOS', 'BOLSA DA PORTA', 'ALARME'],
 ['PAINEL', 'BANCOS', 'ESTRIBO'],
 ['BOLSA DA PORTA', 'ALARME', 'PAINEL'],
 ['PAINEL', 'ALARME', 'BANCOS', 'ESTRIBO']]

In [13]:
te = TransactionEncoder()
te_array = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_array, columns=te.columns_)
df

    ALARME  BANCOS  BOLSA DA PORTA  ESTRIBO  PAINEL
0    False    True            True     True    True
1     True    True            True    False   False
2     True   False           False     True    True
3    False    True           False     True    True
4     True   False            True    False    True
5     True    True           False     True    True
6    False    True            True     True   False
7     True    True           False     True    True
8     True   False            True     True   False
9     True    True           False    False    True
10   False    True            True    False    True
11   False    True           False     True    True
12    True    True            True     True   False
13    True    True           False     True    True
14    True   False            True     True    True
15    True    True           False     True   False
16    True    True            True    False   False
17   False    True           False     True    True
18    True   False            True    False    True
19    True    True           False     True    True

In [14]:
#suporte mínino 50%
#confiança mínima 50%

frequent_itemsets = apriori(df, min_support=0.5, use_colnames=True)
frequent_itemsets

   support           itemsets
0     0.70           (ALARME)
1     0.75           (BANCOS)
2     0.50   (BOLSA DA PORTA)
3     0.70          (ESTRIBO)
4     0.70           (PAINEL)
5     0.55  (BANCOS, ESTRIBO)
6     0.50   (BANCOS, PAINEL)
7     0.50  (PAINEL, ESTRIBO)